### ISSUE TITLE
Warning handler crashes under py2

### ISSUE THREAD

**Issue by shaunix** [itstool/itstool#25]
If there's an invalid translation, and the source string contains non-ascii, and you use python 2, you get an error.

https://gitlab.gnome.org/GNOME/gnome-user-docs/issues/23

Solution might be to replace `encode('utf-8')` with `ustr` on lines 1062 and 1089.

**Comment by ortolot** [comment]
Hello,

Since msgstr is already an unicode, there is no need to encode it or do anything with it before adding it to the formatted unicode string.

If you want to pull it, I have corrected it in git://git.ortolo.eu/pkg-itstool.git branch contrib/fix_decode_crash. You can apply it with:

git pull git://git.ortolo.eu/pkg-itstool.git contrib/fix_decode_crash

Or, if you prefer to use HTTP:

git pull https://git.ortolo.eu/git/pkg-itstool.git contrib/fix_decode_crash

Regards,

-- 
Tanguy Ortolo

**Comment by belegdol** [comment]
Hello @ortolot,
I tried to fix Fedora build using the updated patch from Debian 2.0.5-2, but unfortunately it still does not work:
```
Core was generated by `/usr/bin/python3 -s /usr/bin/itstool -m ../cs/cs.mo ..//C/gnumeric.xml'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fdbf2e04a75 in function_code_fastcall (globals=<optimized out>, nargs=2, args=0x7fdbe2c713e8, co=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:280
#1  _PyFunction_FastCallDict (func=<optimized out>, args=0x7fdbe2c713e0, nargs=2, kwargs=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:322
#2  0x00007fdbe50c6226 in libxml_xmlErrorFuncHandler (ctx=<optimized out>, msg=<optimized out>) at ../../python/libxml.c:1644
#3  0x00007fdbe4f62abd in xmlParserPrintFileContextInternal (input=input@entry=0x5646e026df20, 
    channel=channel@entry=0x7fdbe50c60e0 <libxml_xmlErrorFuncHandler>, data=data@entry=0x0) at ../error.c:208
#4  0x00007fdbe4f62ef7 in xmlReportError (err=err@entry=0x5646e02bb1a8, ctxt=ctxt@entry=0x5646e02baf50, 
    str=str@entry=0x5646e02c9080 "Opening and ending tag mismatch: guilabel line 170 and para\n", 
    channel=0x7fdbe50c60e0 <libxml_xmlErrorFuncHandler>, channel@entry=0x0, data=data@entry=0x0) at ../error.c:406
#5  0x00007fdbe4f647d3 in __xmlRaiseError (schannel=schannel@entry=0x0, channel=0x7fdbe4f63590 <xmlParserError__internal_alias>, 
    channel@entry=0x0, data=0x5646e02baf50, data@entry=0x0, ctx=ctx@entry=0x5646e02baf50, nod=nod@entry=0x0, 
    domain=domain@entry=1, code=76, level=XML_ERR_FATAL, file=<optimized out>, line=170, str1=<optimized out>, 
    str2=<optimized out>, str3=<optimized out>, int1=170, col=490, msg=<optimized out>) at ../error.c:633
#6  0x00007fdbe4f691c5 in xmlFatalErrMsgStrIntStr (ctxt=0x5646e02baf50, error=<optimized out>, msg=<optimized out>, 
    str1=<optimized out>, val=<optimized out>, str2=<optimized out>) at ../parser.c:711
#7  0x00007fdbe4f76f45 in xmlParseEndTag2 (ctxt=ctxt@entry=0x5646e02baf50, prefix=0x0, URI=0x0, line=line@entry=170, nsNr=0, 
    tlen=<optimized out>) at ../parser.c:9669
#8  0x00007fdbe4f7babc in xmlParseElement__internal_alias (ctxt=ctxt@entry=0x5646e02baf50) at ../parser.c:10037
#9  0x00007fdbe4f7b1a6 in xmlParseContent__internal_alias (ctxt=0x5646e02baf50) at ../parser.c:9846
#10 0x00007fdbe4f7ba59 in xmlParseElement__internal_alias (ctxt=ctxt@entry=0x5646e02baf50) at ../parser.c:10014
#11 0x00007fdbe4f7b1a6 in xmlParseContent__internal_alias (ctxt=0x5646e02baf50) at ../parser.c:9846
#12 0x00007fdbe4f7ba59 in xmlParseElement__internal_alias (ctxt=ctxt@entry=0x5646e02baf50) at ../parser.c:10014
#13 0x00007fdbe4f7c15a in xmlParseDocument__internal_alias (ctxt=0x5646e02baf50) at ../parser.c:10711
#14 0x00007fdbe50d4d36 in libxml_xmlParseDocument (self=self@entry=<module at remote 0x7fdbe54b6f98>, 
    args=args@entry=(<PyCapsule at remote 0x7fdbe2c878a0>,)) at ../../python/libxml2-py.c:4958
#15 0x00007fdbf2e4bf17 in _PyMethodDef_RawFastCallKeywords (method=0x7fdbe50fd7e0 <libxmlMethods+9792>, 
    self=<module at remote 0x7fdbe54b6f98>, args=0x7fdbe4a54530, nargs=<optimized out>, kwnames=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:694
#16 0x00007fdbf2e4c1b0 in _PyCFunction_FastCallKeywords (
    func=<built-in method xmlParseDocument of module object at remote 0x7fdbe54b6f98>, args=<optimized out>, 
    nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:730
#17 0x00007fdbf2ec3acc in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4554
#18 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3093
#19 0x00007fdbf2e4b78a in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:408
#20 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x5646e02c31e8, nargs=1, kwnames=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:408
#21 0x00007fdbf2ebe1d1 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#22 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3110
#23 0x00007fdbf2e038e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x7fdbe578c120, kwargs=0x5646e0126f00, kwcount=<optimized out>, kwstep=1, defs=0x7fdbe5795560, defcount=2, kwdefs=0x0, closure=0x0, name='get_translated', qualname='Document.get_translated') at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#24 0x00007fdbf2e4b931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x5646e0126ee8, nargs=3, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#25 0x00007fdbf2ebf256 in call_function (kwnames=('strict', 'lang'), oparg=<optimized out>, pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#26 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#27 0x00007fdbf2e038e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x7fdbe578e860, kwargs=0x5646e01e7948, kwcount=<optimized out>, kwstep=1, defs=0x7fdbe57926e0, defcount=2, kwdefs=0x0, closure=0x0, name='merge_translations', qualname='Document.merge_translations') at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#28 0x00007fdbf2e4b931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x5646e01e7930, nargs=3, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#29 0x00007fdbf2ebf256 in call_function (kwnames=('node', 'strict'), oparg=<optimized out>, pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#30 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#31 0x00007fdbf2e038e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x7fdbe578e860, kwargs=0x5646dffb5208, kwcount=<optimized out>, kwstep=1, defs=0x7fdbe57926e0, defcount=2, kwdefs=0x0, closure=0x0, name='merge_translations', qualname='Document.merge_translations') at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#32 0x00007fdbf2e4b931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x5646dffb51f0, nargs=3, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#33 0x00007fdbf2ebf256 in call_function (kwnames=('node', 'strict'), oparg=<optimized out>, pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#34 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#35 0x00007fdbf2e038e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x7fdbe578e860, kwargs=0x5646e01b63a8, kwcount=<optimized out>, kwstep=1, defs=0x7fdbe57926e0, defcount=2, kwdefs=0x0, closure=0x0, name='merge_translations', qualname='Document.merge_translations') at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#36 0x00007fdbf2e4b931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x5646e01b6390, nargs=3, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#37 0x00007fdbf2ebf256 in call_function (kwnames=('node', 'strict'), oparg=<optimized out>, pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#38 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#39 0x00007fdbf2e038e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x7fdbe578e860, kwargs=0x5646dffbaef8, kwcount=<optimized out>, kwstep=1, defs=0x7fdbe57926e0, defcount=2, kwdefs=0x0, closure=0x0, name='merge_translations', qualname='Document.merge_translations') at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#40 0x00007fdbf2e4b931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x5646dffbaee0, nargs=3, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#41 0x00007fdbf2ebf256 in call_function (kwnames=('node', 'strict'), oparg=<optimized out>, pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#42 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#43 0x00007fdbf2e038e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x7fdbe578e860, kwargs=0x5646dd62f238, kwcount=<optimized out>, kwstep=1, defs=0x7fdbe57926e0, defcount=2, kwdefs=0x0, closure=0x0, name='merge_translations', qualname='Document.merge_translations') at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#44 0x00007fdbf2e4b931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x5646dd62f220, nargs=3, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#45 0x00007fdbf2ebf256 in call_function (kwnames=('node', 'strict'), oparg=<optimized out>, pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#46 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#47 0x00007fdbf2e038e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x7fdbe57973a8, kwargs=0x7fdbe591eb80, kwcount=<optimized out>, kwstep=1, defs=0x7fdbe57926e0, defcount=2, kwdefs=0x0, closure=0x0, name='merge_translations', qualname='Document.merge_translations') at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#48 0x00007fdbf2e4b931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7fdbe591eb68, nargs=3, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#49 0x00007fdbf2ebf256 in call_function (kwnames=('strict',), oparg=<optimized out>, pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#50 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#51 0x00007fdbf2e038e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=0x0, kwargs=0x0, kwcount=<optimized out>, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#52 0x00007fdbf2e04983 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3959
#53 0x00007fdbf2e049ab in PyEval_EvalCode (co=co@entry=<code at remote 0x7fdbe5793150>, globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/itstool') at remote 0x7fdbe58b2518>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fdbe5976c28>, '__file__': '/usr/bin/itstool', '__cached__': None, 'print_function': <_Feature(optional=(2, 6, 0, 'alpha', 2), mandatory=(3, 0, 0, 'alpha', 0), compiler_flag=65536) at remote 0x7fdbe53f4710>, 'unicode_literals': <_Feature(optional=(...), mandatory=(...), compiler_flag=131072) at remote 0x7fdbe53f4748>, 'VERSION': '2.0.5', 'DATADIR': '/usr/share', 'gettext': <module at remote 0x7fdbe53e5688>, 'hashlib': <module at remote 0x7fdbe5721cc8>, 'libxml2': <module at remote 0x7fdbe5721e08>, 'optparse': <module at remote 0x7fdbe5739ae8>, 'os': <module at remote 0x7fdbe58b7db8>, 're': <module at remote 0x7fdbe53ff778>, 'sys': <module at remote 0x7fdbe5970f98>, 'time': <module at remote 0x7fdbe546fd18>, 'io': <module at remote 0x7fdbe58ad778>, 'PY3': True, 'string_type...(truncated), locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/itstool') at remote 0x7fdbe58b2518>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fdbe5976c28>, '__file__': '/usr/bin/itstool', '__cached__': None, 'print_function': <_Feature(optional=(2, 6, 0, 'alpha', 2), mandatory=(3, 0, 0, 'alpha', 0), compiler_flag=65536) at remote 0x7fdbe53f4710>, 'unicode_literals': <_Feature(optional=(...), mandatory=(...), compiler_flag=131072) at remote 0x7fdbe53f4748>, 'VERSION': '2.0.5', 'DATADIR': '/usr/share', 'gettext': <module at remote 0x7fdbe53e5688>, 'hashlib': <module at remote 0x7fdbe5721cc8>, 'libxml2': <module at remote 0x7fdbe5721e08>, 'optparse': <module at remote 0x7fdbe5739ae8>, 'os': <module at remote 0x7fdbe58b7db8>, 're': <module at remote 0x7fdbe53ff778>, 'sys': <module at remote 0x7fdbe5970f98>, 'time': <module at remote 0x7fdbe546fd18>, 'io': <module at remote 0x7fdbe58ad778>, 'PY3': True, 'string_type...(truncated)) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:524
#54 0x00007fdbf2f3320e in run_mod (mod=mod@entry=0x5646dd3c35a0, filename=filename@entry='/usr/bin/itstool', globals=globals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/itstool') at remote 0x7fdbe58b2518>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fdbe5976c28>, '__file__': '/usr/bin/itstool', '__cached__': None, 'print_function': <_Feature(optional=(2, 6, 0, 'alpha', 2), mandatory=(3, 0, 0, 'alpha', 0), compiler_flag=65536) at remote 0x7fdbe53f4710>, 'unicode_literals': <_Feature(optional=(...), mandatory=(...), compiler_flag=131072) at remote 0x7fdbe53f4748>, 'VERSION': '2.0.5', 'DATADIR': '/usr/share', 'gettext': <module at remote 0x7fdbe53e5688>, 'hashlib': <module at remote 0x7fdbe5721cc8>, 'libxml2': <module at remote 0x7fdbe5721e08>, 'optparse': <module at remote 0x7fdbe5739ae8>, 'os': <module at remote 0x7fdbe58b7db8>, 're': <module at remote 0x7fdbe53ff778>, 'sys': <module at remote 0x7fdbe5970f98>, 'time': <module at remote 0x7fdbe546fd18>, 'io': <module at remote 0x7fdbe58ad778>, 'PY3': True, 'string_type...(truncated), locals=locals@entry={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/itstool') at remote 0x7fdbe58b2518>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fdbe5976c28>, '__file__': '/usr/bin/itstool', '__cached__': None, 'print_function': <_Feature(optional=(2, 6, 0, 'alpha', 2), mandatory=(3, 0, 0, 'alpha', 0), compiler_flag=65536) at remote 0x7fdbe53f4710>, 'unicode_literals': <_Feature(optional=(...), mandatory=(...), compiler_flag=131072) at remote 0x7fdbe53f4748>, 'VERSION': '2.0.5', 'DATADIR': '/usr/share', 'gettext': <module at remote 0x7fdbe53e5688>, 'hashlib': <module at remote 0x7fdbe5721cc8>, 'libxml2': <module at remote 0x7fdbe5721e08>, 'optparse': <module at remote 0x7fdbe5739ae8>, 'os': <module at remote 0x7fdbe58b7db8>, 're': <module at remote 0x7fdbe53ff778>, 'sys': <module at remote 0x7fdbe5970f98>, 'time': <module at remote 0x7fdbe546fd18>, 'io': <module at remote 0x7fdbe58ad778>, 'PY3': True, 'string_type...(truncated), flags=flags@entry=0x7ffd063935e0, arena=arena@entry=0x7fdbe597e0a8) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/pythonrun.c:1035
#55 0x00007fdbf2f35086 in PyRun_FileExFlags (fp=0x5646dd2efc40, filename_str=<optimized out>, start=<optimized out>, globals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/itstool') at remote 0x7fdbe58b2518>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fdbe5976c28>, '__file__': '/usr/bin/itstool', '__cached__': None, 'print_function': <_Feature(optional=(2, 6, 0, 'alpha', 2), mandatory=(3, 0, 0, 'alpha', 0), compiler_flag=65536) at remote 0x7fdbe53f4710>, 'unicode_literals': <_Feature(optional=(...), mandatory=(...), compiler_flag=131072) at remote 0x7fdbe53f4748>, 'VERSION': '2.0.5', 'DATADIR': '/usr/share', 'gettext': <module at remote 0x7fdbe53e5688>, 'hashlib': <module at remote 0x7fdbe5721cc8>, 'libxml2': <module at remote 0x7fdbe5721e08>, 'optparse': <module at remote 0x7fdbe5739ae8>, 'os': <module at remote 0x7fdbe58b7db8>, 're': <module at remote 0x7fdbe53ff778>, 'sys': <module at remote 0x7fdbe5970f98>, 'time': <module at remote 0x7fdbe546fd18>, 'io': <module at remote 0x7fdbe58ad778>, 'PY3': True, 'string_type...(truncated), locals={'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <SourceFileLoader(name='__main__', path='/usr/bin/itstool') at remote 0x7fdbe58b2518>, '__spec__': None, '__annotations__': {}, '__builtins__': <module at remote 0x7fdbe5976c28>, '__file__': '/usr/bin/itstool', '__cached__': None, 'print_function': <_Feature(optional=(2, 6, 0, 'alpha', 2), mandatory=(3, 0, 0, 'alpha', 0), compiler_flag=65536) at remote 0x7fdbe53f4710>, 'unicode_literals': <_Feature(optional=(...), mandatory=(...), compiler_flag=131072) at remote 0x7fdbe53f4748>, 'VERSION': '2.0.5', 'DATADIR': '/usr/share', 'gettext': <module at remote 0x7fdbe53e5688>, 'hashlib': <module at remote 0x7fdbe5721cc8>, 'libxml2': <module at remote 0x7fdbe5721e08>, 'optparse': <module at remote 0x7fdbe5739ae8>, 'os': <module at remote 0x7fdbe58b7db8>, 're': <module at remote 0x7fdbe53ff778>, 'sys': <module at remote 0x7fdbe5970f98>, 'time': <module at remote 0x7fdbe546fd18>, 'io': <module at remote 0x7fdbe58ad778>, 'PY3': True, 'string_type...(truncated), closeit=1, flags=0x7ffd063935e0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/pythonrun.c:988
#56 0x00007fdbf2f36648 in PyRun_SimpleFileExFlags (fp=0x5646dd2efc40, filename=<optimized out>, closeit=1, flags=0x7ffd063935e0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/pythonrun.c:429
#57 0x00007fdbf2f38801 in pymain_run_file (p_cf=0x7ffd063935e0, filename=0x5646dd2a6540 L"/usr/bin/itstool", fp=0x5646dd2efc40) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:427
#58 pymain_run_filename (cf=0x7ffd063935e0, pymain=0x7ffd063936f0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:1537
#59 pymain_run_python (pymain=0x7ffd063936f0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:2626
#60 pymain_main (pymain=<optimized out>, pymain=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:2787
#61 0x00007fdbf2f38bdc in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:2822
#62 0x00007fdbf29a6413 in __libc_start_main (main=0x5646dc929050 <main>, argc=6, argv=0x7ffd06393848, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd06393838) at ../csu/libc-start.c:308
#63 0x00005646dc92908e in _start ()
```
